# Generated by Django 4.1.2 on 2022-10-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('journal_name', models.TextField()),
                ('pub_year', models.IntegerField()),
                ('num_of_citation', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchextractor.author', verbose_name='authors')),
            ],
        ),
    ]
